# Generated by Django 3.0.8 on 2020-08-05 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('starting_bid', models.IntegerField()),
                ('img_url', models.TextField()),
                ('category', models.CharField(choices=[('ART', 'Collectibles & Art'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home & Garden'), ('PARTS', 'Parts & Accesories'), ('MUSICAL', 'Musical Instruments & gear'), ('SPORT', 'Sporting goods'), ('TOYS', 'Toys & Hobbies'), ('UNKNOWN', 'Other categories')], max_length=11)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_dt', models.DateTimeField(auto_now_add=True)),
                ('comment_auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auctions')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auctions')),
                ('bid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
