# Generated by Django 3.0.8 on 2020-08-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img_url',
            field=models.TextField(default=None),
        ),
    ]
