# Generated by Django 3.0.8 on 2020-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200808_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('ART', 'Collectibles & Art'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME', 'Home & Garden'), ('PARTS', 'Parts & Accesories'), ('MUSICAL', 'Musical Instruments & gear'), ('SPORT', 'Sporting goods'), ('TOYS', 'Toys & Hobbies'), (None, 'Other categories')], default=None, max_length=11),
        ),
    ]
