# Generated by Django 3.0.8 on 2020-08-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist',
            new_name='wishlist_auction',
        ),
    ]
