# Generated by Django 3.0.8 on 2020-08-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200810_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishlist_auction',
            field=models.ManyToManyField(blank=True, to='auctions.Auction'),
        ),
    ]
